add git developer OAuth client Id and secret in header when calling github api
sifatul/find-profile pull request #52
Opened 2022-08-21 16:41 UTC by fazlerabby07

2022-08-22 00:08 UTC, sifatul requested changes

2022-08-22 00:08 UTC, sifatul commented on Utils/fetchData.tsx
> +        console.log(url, profileUrl, headers);
@fazleteraark please remove console.log

2022-08-22 00:08 UTC, sifatul commented on pages/api/forward-api.ts
> +    console.log(headers);
@fazlerabby07 please remove header

2022-08-22 00:09 UTC, sifatul commented
@fazlerabby07 it looks unsafe as headers will be exposed in browser and header contains secret values. is it the best way to do?

2022-08-23 04:38 UTC, fazlerabby07 commented
@sifatul fix the headers when we call github api. now we convert the github clinet and secret into base64 string.

2022-08-23 23:37 UTC, merged