wip: create user profile
sifatul/find-profile pull request #57
Opened 2022-08-24 17:49 UTC by JRakin

WIP: create user profile

2022-08-24 23:05 UTC, sifatul commented on components/form/basicInfoForm.tsx
> +    email: Yup.string().email('Invalid email').required('Required'),
@JRakin use a email validation.

2022-08-24 23:06 UTC, sifatul commented on components/form/profilesForm.tsx
> +    linkedin_url: Yup.string().url('Invalid url').required('Required'),
@JRakin use url validation

2022-08-24 23:07 UTC, sifatul commented on components/form/profilesForm.tsx
> +    codepen_url: Yup.string().url(),
@JRakin also check whether url is codepen url or wrong domain url

2022-08-24 23:10 UTC, sifatul requested changes

2022-08-24 23:10 UTC, sifatul commented on pages/api/users/add.ts
> +enum Gender {
@JRakin can we put gender in a golobal enum so that it can be refereed later for other pages

2022-08-24 23:10 UTC, sifatul commented on pages/api/users/models/UserSchema.ts
> +    FEMALE = 'female',
@JRakin already has the enum in another page.

2022-08-24 23:10 UTC, sifatul commented on pages/api/users/models/UserSchema.ts
> +            required: [true, 'Email is required'],
@JRakin email validation

2022-08-24 23:10 UTC, sifatul commented on pages/api/users/models/UserSchema.ts
> +        codepen_url: { type: String },
@JRakin same like frontend url validation

2022-08-30 23:10 UTC, sifatul requested changes

2022-08-30 23:10 UTC, sifatul commented on components/form/createProfileMain.tsx
> +                                <Typography variant='subtitle1'>
@JRakin instead of writing tertiary condition inside markup better to make separate components

2022-08-30 23:10 UTC, sifatul commented on components/form/basicInfoForm.tsx
> +            /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
@JRakin we are already using a method `isEmail` in search.hook.tsx. Let's use same method all places

2022-08-30 23:10 UTC, sifatul commented on components/form/profilesForm.tsx
> +        /^(https?:\/\/)?(www\.)?github\.com\/[a-zA-Z0-9_]{1,25}$/gim,
@JRakin can you please move the checks to a common helper? we can re-use them in other pages.

2022-08-30 23:10 UTC, sifatul commented on pages/api/users/models/UserSchema.ts
> +import isEmail from 'validator/lib/isEmail';
@JRakin we don't need to use any third party package for validation. We have our own 
https://www.npmjs.com/package/js-string-helper

2022-09-03 20:55 UTC, JRakin commented
@sifatul vaiya i have added mongoose we need to connect to db using mongoose in other components i will change those as well

2022-09-03 20:56 UTC, JRakin commented
and also I have created some reusable component using formik and mui

2022-09-04 02:23 UTC, sifatul requested changes

2022-09-04 02:23 UTC, sifatul commented on helper/regex.ts
> +export const leetcodeUrlRegex = /^(https?:\/\/)?(www\.)?leetcode\.com\/[a-zA-Z0-9_]{1,25}$/gim;
@JRakin please use a name thats more understanding. like get,set,fetch etc. naming like `leetcodeUrlRegex` is hard to understand what it does

2022-09-04 14:26 UTC, merged